### ISSUE TITLE
pretrained vgg19

### ISSUE THREAD

**Issue by aliericcantona** [vinthony/ghost-free-shadow-removal#10]
Hi,

Can you point out to the vgg pretrained model to download? Looks like that model no longer part of the url you provided. 

Thanks

**Comment by vinthony** [comment]
Thanks for your attention.

The link is still on that page.

However, you can directly download the vgg19 [here](https://www.vlfeat.org/matconvnet/models/imagenet-vgg-verydeep-19.mat).

**Comment by aliericcantona** [comment]
1. Do you need to run Jupyter? I tried to add one image to the samples folder and did not run the new image. 
2. the tensorflow is old version, the new version does not have tensorflow.contrib.
3. Is there any python code that I can run against a new image only ...
Python evaluate.py new_image.jpg, is that train_sr.py the one. How can I run that?

**Comment by aliericcantona** [comment]
The code does not work tf version 2.0

Then, I downgraded the tensorflow to 1.14.0
....

I ran this command
 python3 train_sr.py --task Models/srdplus-pretrained  --data_dir Samples/  --use_gpu 0 --is_training 0

Am I missing something here?


**Error ...

Traceback (most recent call last):
  File "train_sr.py", line 52, in <module>
    
shadow_free_image,predicted_mask=build_aggasatt_joint(input,channel,vgg_19_path=vgg_19_path)
(Pdb)  

failed on this line
[i] Hypercolumn ON, building hypercolumn features ... 
*** TypeError: expected str, bytes or os.PathLike object, not dict

**Comment by aliericcantona** [comment]
but the code does not work tf version 2.0

**Comment by aliericcantona** [comment]
I fixed the error. You have a bug in the network code. 
Line 34 of train_sr.py 

change it to 
vgg_19_path = './Models/imagenet-vgg-verydeep-19.mat'

**Comment by aliericcantona** [comment]
the next error is 

[i] contain checkpoint:  None
Traceback (most recent call last):
  File "train_sr.py", line 97, in <module>
    print('loaded '+ckpt.model_checkpoint_path)
AttributeError: 'NoneType' object has no attribute 'model_checkpoint_path'

**Comment by aliericcantona** [comment]
Fixed that too ...
you sould copy Models/srdplus-pretrained ---> logs/Models/srdplus-pretrained

**Comment by aliericcantona** [comment]
python3 train_sr.py --task Models/srdplus-pretrained --data_dir Samples/ --use_gpu 0 --is_training 0

Where do I see the removed shadows from images, does your code generate and output_dir?

**Comment by aliericcantona** [comment]
I think there is a folder structure for data_dir on the command line that code needs. Can you tell me how I can correct based on your Samples/ 

python3 train_sr.py --task Models/srdplus-pretrained --data_dir Samples/ --use_gpu 0 --is_training 0 (This is not correct data_dir  for the code)

**Comment by aliericcantona** [comment]
I think you need some certain structure for the data_dir to get your proper output. Can you elaborate on that. 
I need simple data_dir (folder) ---> using your code ---> output_dir removed shadows. I think the code needs to be modified a  bit.

**Comment by aliericcantona** [comment]
I made test_A, test_B, test_T all the same and inside copied Samples images . why do I need these three folders? I can get something out of the network finally. 

Can you possibly explain more. I can help you out to simplify your code. Not easy to use to be honest. 

And the network is super slow without GPU is around 52second per image of 640x480.

**Comment by aliericcantona** [comment]
I could generate the images but did not understand why you need three set of folders to generate the output. If you elaborate more I will help you out to simplify the code and be more user friendly.

**Comment by vinthony** [comment]
Sorry for the inconvenience.

1.  Sure, you need to use the TensorFlow 1.x

2. about the test, I have made an online [demo](https://colab.research.google.com/drive/1cJ_dsBUXFaFtjoZB9gDYeahjmysnvnTq) or a local Jupiter notebook(demo.ipynb) for testing by just clicking the running button. Directly testing from the command line is not recommended currently, You should train the code and test them by the command line.

3. I don't need three folders for testing. However, my data loader loads them at once. Thus, if you only want  to inference the network, you can try to reimplement the `prepare_image` function in `util.py`

4. Still thanks for your opinion, I will try to make the code more smooth.

5. Our network is pretty heavy because of the hyper-features in VGG19 and dilated convolutions.  A much better algorithm is working on and will be open-sourced upon publication.

**Comment by aliericcantona** [comment]
3. your version of prepare_image relies on the three folders. I tried to only use one but I had a bit problem with creating the tf image.
4. No problem. I am here to help once Ph.D. Student and now more of product software engineer and startuper.
5. Got it.

**Comment by vinthony** [comment]
Or in the testing, you can just loop the folder and read the images by OpenCV.

The following code is directly from the demo:

```
import os,cv2
# some samples results.
plt.rcParams["figure.figsize"] = (24,6)

for img_path in [os.path.join(sample_path,x) for x in os.listdir(sample_path) if '.jpg' in x or '.png' in x]:

    plt.figure()
    plt.axis('off')
    
    iminput=cv2.imread(img_path,-1)
    imoutput = sess.run(shadow_free_image,feed_dict={input:np.expand_dims(iminput/255.,axis=0)})
    imoutput = np.uint8(np.squeeze(np.minimum(np.maximum(imoutput[0],0.0),1.0))*255.0)
    imcompare = np.concatenate([iminput,imoutput],axis=1)

    # bgr->rgb
    plt.imshow(imcompare[...,::-1])
    plt.show()

```

**Comment by aliericcantona** [comment]
awesome I will add that tomorrow to my code.
