### ISSUE TITLE
SRD Mask is not available?

### ISSUE THREAD

**Issue by howardgriffin** [vinthony/ghost-free-shadow-removal#11]
SRD mask link seems to be  unreachable. And what is the mask look like? the value of shadow mask area is 0 or 255?

**Comment by vinthony** [comment]
Hi, the value of the shadow mask area is 255.

and the SRD mask is still available in [this link](https://uofmacau-my.sharepoint.com/personal/yb87432_umac_mo/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fyb87432%5Fumac%5Fmo%2FDocuments%2Fghost%2Dfree%2Dshadow%2Dremoval%2Fsrd%5Fmask%2Ezip&parent=%2Fpersonal%2Fyb87432%5Fumac%5Fmo%2FDocuments%2Fghost%2Dfree%2Dshadow%2Dremoval&originalPath=aHR0cHM6Ly91b2ZtYWNhdS1teS5zaGFyZXBvaW50LmNvbS86dTovZy9wZXJzb25hbC95Yjg3NDMyX3VtYWNfbW8vRVo4Q2lJaE5BRGxBa0E0RmhpbV9RemdCZkRlSTdxZFVydDZ3djJFVnhaU2Mydz9ydGltZT1CQTMyUENqMDEwZw).

you can find the discussion about the mask in SRD here:

https://github.com/vinthony/ghost-free-shadow-removal/issues/4#issuecomment-583969076
