### ISSUE TITLE
Why resizing here?

### ISSUE THREAD

**Issue by aliericcantona** [vinthony/ghost-free-shadow-removal#12]
https://github.com/vinthony/ghost-free-shadow-removal/blob/42579ef014ef524d8cc107986c839cfb0ccefde1/networks.py#L146

This will slow down process again, no?

**Comment by vinthony** [comment]
Hi, thanks for your attention.

Our network aims to design a better network to remove the shadow from the image processing aspect. 

Traditional UNet like structures will fail to learn the partially degraded regions specifically even with a skip-connection.(See more on [PConv](https://arxiv.org/abs/1804.07723), [S2AM](https://arxiv.org/abs/1907.06406)).

Thus,  to get benefits from the higher-level features and avoid the down-scaling, we resize the high-level features to the full resolution and gives guidance to the image processing task.
