### ISSUE TITLE
questions about perceptual loss weight

### ISSUE THREAD

**Issue by howardgriffin** [vinthony/ghost-free-shadow-removal#14]
Hi, I am confused of the different weight  of each vgg layer's perceptual loss , and the GAN loss weight seems to be very low compared with  other loss. Could you make some explanation?

**Comment by vinthony** [comment]
Hi, thanks for your attention.

The weights of the perceptual loss are taken from the previous work on [reflection removal](https://github.com/ceciliavision/perceptual-reflection-removal).

GAN plays as a regularization for our task and aims to fit the overall distribution. Thus, if we use a larger GAN loss, the output will not be produced as expected compared to the ground truth. and, we still want our network to mainly focus on pixel-wise restoration. The weight of GAN loss follows [Pix2Pix](https://phillipi.github.io/pix2pix/) and more details are discussed in that paper.
