### ISSUE TITLE
Not possible to download models

### ISSUE THREAD

**Issue by Wojak27** [vinthony/ghost-free-shadow-removal#18]
Hi! I wanted to test your network on my own pc, but when I tried to download the model I have gotten the file too large to download error on sharepoint. Is there any possibility you could host the models in some other way?

**Comment by vinthony** [comment]
Hi, thanks for your attention to our work.

It is weird but the pretrained model can also be downloaded from [google driver](https://drive.google.com/file/d/1rEIWWLwEpbZGPyFUc9jSIQr78ZeQy5eZ/view?usp=sharing)

**Comment by Wojak27** [comment]
> Hi, thanks for your attention to our work.
> 
> It is weird but the pretrained model can also be downloaded from [google driver](https://drive.google.com/file/d/1rEIWWLwEpbZGPyFUc9jSIQr78ZeQy5eZ/view?usp=sharing)

Thank you!
