### ISSUE TITLE
Unreachable link to a model provided

### ISSUE THREAD

**Issue by naoto0804** [vinthony/ghost-free-shadow-removal#2]
In [#resources](https://github.com/vinthony/ghost-free-shadow-removal#resources), the link to one of the models provided [ISTD+](https://uofmacau-my.sharepoint.com/:u:/g/personal/yb87432_umac_mo/ERvQFx8d8AxLmrafMi609nMBYGx9206dlVb5og2Sy0m90A?e=SOrO0R) seems to be invalid. Could you share the right one?

**Comment by vinthony** [comment]
Hi, this link seems to the results of ISTD+. I have re-share it and the new link is https://uofmacau-my.sharepoint.com/:u:/g/personal/yb87432_umac_mo/ERvQFx8d8AxLmrafMi609nMBo7JnsV4a4s63FV_NP89_eA

**Comment by naoto0804** [comment]
Thank you so much again!
