### ISSUE TITLE
about the detection mask of ISTD dataset

### ISSUE THREAD

**Issue by fl82hope** [vinthony/ghost-free-shadow-removal#26]
Great work! It is really helpful.

Could you share me with the detection mask on the ISTD dataset? I used a method not same as yours for the mask detection, but it is not accurate enough. I want to have a look at the detected masks. Thanks in advance.

my email is lanf@email.sc.edu.

**Comment by vinthony** [comment]
hi, I have received your email and the detection mask will be sent to you in a few days.

**Comment by vinthony** [comment]
please check the email.
