### ISSUE TITLE
I can't generate synthesized shadow

### ISSUE THREAD

**Issue by mathdoug** [vinthony/ghost-free-shadow-removal#27]
First of all, congratulations! 

I'm trying to generate synthesized shadow but I get some errors. I did what you said in README for training the GAN model. But your code in train_ss.py doesn't specify the vgg_19_path in the line 56. I get this error:

FileNotFoundError: [Errno 2] No such file or directory: 'None.mat'

Do I have to use the imagenet-vgg-verydeep-19.mat ?

**Comment by vinthony** [comment]
Sorry about that, you need to specify the path of `imagenet-vgg-verydeep-19.mat` to calculate the deep perceptual loss.
