### ISSUE TITLE
ValueError: Cannot feed value of shape (1, 480, 640) for Tensor 'Placeholder:0', which has shape '(?, ?, ?, 3)'

### ISSUE THREAD

**Issue by landkwon94** [vinthony/ghost-free-shadow-removal#28]
Hello~ before I talk about my Issue, I want to say Thank you for providing beautiful code.

As I tried to start studying your code from  " shadow_removal.ipynb ", such an error occured.

![image](https://user-images.githubusercontent.com/73383617/105816981-58b95080-5ff8-11eb-9c9d-cfbb05d91d53.png)

This is starting point of your code, so I thought that I missed something. But I could not fix this problem... Can you help me?
(I tried to open this code by Colab.)

Or are there any changes in your code compared to the model which was released in the past?

**Comment by vinthony** [comment]
Hi, Thanks for pointing that out.

It happens because I have added some binary mask images to the `sample` folder for the shadow synthesis demo.

It has been fixed.

**Comment by landkwon94** [comment]
Thank you so much :)
