### ISSUE TITLE
關於架構圖的一些問題

### ISSUE THREAD

**Issue by Yi-Hung-Sung** [vinthony/ghost-free-shadow-removal#29]
樓主您好，關於架構圖我有一些問題想請教一下:
1.請問aggreatation部分，上(feature)下(attention)兩部分，設定上有什麼不同，才能有各自不同的功能?
![架構圖](https://user-images.githubusercontent.com/77673840/108364371-f6d3bb80-7230-11eb-91bb-fe06dd630a32.jpg)
2.請問2個紅色圈圈部分會有怎麼樣的輸出?
再麻煩您了。

**Comment by vinthony** [comment]
Hi,

1. 上下两个部分的架构是相同的，但是aggreatation node是不共享权重的。由于不同支路监督的存在，我们的网络希望共享的dilated-conv学到相同的特征，而让aggreatation node学习到不同任务特有的特征.

2. 因为我们在网络的前半部分只使用了dilated convolution. 红色部分的输出应该和输入相同，假如你输入的图像为BatchSize x 3 x height x width, 输出应该也是 BatchSize x C x height x width. 这里C是你所规定的前一个卷积的channel.

希望能帮到您。

**Comment by Yi-Hung-Sung** [comment]
了解了，非常感謝您的幫忙。
