### ISSUE TITLE
楼主你好，阴影合成网络训练效果不佳

### ISSUE THREAD

**Issue by ersanliqiao** [vinthony/ghost-free-shadow-removal#3]
楼主你好，能说一说阴影合成网络的具体训练参数吗？我这边复现效果并不好，另外，为什么训练batch_size都是1？我训练下来，生成器loss不收敛

**Comment by vinthony** [comment]
您好，感谢您的关注。训练效果不佳不知道是哪方面?
本文注重于验证用GAN生成的阴影能够对removal和detection都有帮助。
所有的参数应该都是默认参数。
Batch_size 等于1的原因是因为在训练过程中，我们随机resize了图片到[256,480]来保持aspect radio不变，batch_size>1不能够训练。
生成器的loss主要看preception loss，在此训练过程中，preception loss 会逐渐下降。
这里我们采用了类似于pix2pix的训练方法，循环100epoch来进行shadow合成。合成的部分阴影可以参考readme： https://github.com/vinthony/ghost-free-shadow-removal#resources

**Comment by ersanliqiao** [comment]
阴影合成的效果不佳

**Comment by vinthony** [comment]
您好，请问您这里是如何定义阴影合成的“效果”呢？是SSIM，PSNR还是？
或者是相比于哪个baseline效果不佳呢？有没有训练中生成的阴影图作为证据？
如果只是说”不佳“让我有点不知道是哪方面的问题。😁

**Comment by ersanliqiao** [comment]
楼主你好，train_ss.py里面输入输出反了，train_A是带shadow图,  train_C才是shadow free图

**Comment by ersanliqiao** [comment]
另外，train_ss.py里面要from discriminator import build_discriminator一行改成从networks.py导入

**Comment by vinthony** [comment]
谢谢指正，这部分代码应该是整理的时候出了一些问题。已经改过了。

**Comment by ersanliqiao** [comment]
101行那部分，train_A和train_C分别是ISTD数据集的阴影图和无阴影图，这两部分代码里面也是反了的

**Comment by vinthony** [comment]
您好只需要更改送进去graph的iminput和imtarget的顺序即可，整个代码是使用train_A来作为index的，101行用来读取，util的prepare_image用字符串replace的方式得到train_B和train_C, 这部分不可以更改。

**Comment by ersanliqiao** [comment]
这样是可以的，不过楼主可以把这部分细节在readme部分写详细一点，其他人可能也会容易误解

**Comment by vinthony** [comment]
好的， 谢谢提醒。
