### ISSUE TITLE
How to save predict_mask to png?

### ISSUE THREAD

**Issue by qpaozixu** [vinthony/ghost-free-shadow-removal#39]
HI, your work is well, I want to save the predict_mask to png, how could I do?
Thanks for your help!

**Comment by vinthony** [comment]
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/4397546/158842463-1833a073-5984-41ad-9a1a-205c2acd9a29.png">


run the [colab]( https://colab.research.google.com/drive/1cJ_dsBUXFaFtjoZB9gDYeahjmysnvnTq?usp=sharing#scrollTo=SxF4uQHmEiv0) and add some similar code as in line 18
