### ISSUE TITLE
Demo not performing as hoped

### ISSUE THREAD

**Issue by controlengineerinMLlearning** [vinthony/ghost-free-shadow-removal#41]
Dear Vinthony,

Unfortunately, the Demo is not working as I had hoped. The results I am currently getting are:
![image](https://user-images.githubusercontent.com/58595076/158815518-66804e92-5b49-483a-b057-13f5d180e873.png)

I followed the read-me completely (and have the correct requirements). Do you have any idea how to solve this?

Thank you in advance!

D

**Comment by vinthony** [comment]
Hi, I rerun the online [demo](https://colab.research.google.com/drive/1cJ_dsBUXFaFtjoZB9gDYeahjmysnvnTq?usp=sharing#scrollTo=SxF4uQHmEiv0)， the code works as hoped.  Maybe you can run the colab demo instead. 

Later, I will check the demo ipynb code.

**Comment by controlengineerinMLlearning** [comment]
Dear Vinthony,
I found the error after some debugging. There was somesort of communication error between loading (the pre-trained model) and the conda environment. Reinstalling solved the problem.

Thanks for your review!
