### ISSUE TITLE
Shadow-mask retrieval

### ISSUE THREAD

**Issue by controlengineerinMLlearning** [vinthony/ghost-free-shadow-removal#42]
Hi Vinthony!

Is it possible to retrieve the masks generated from the code? I have not been able to find them.

kind regards,
D

**Comment by vinthony** [comment]
Hi, the code about the mask generation is missing. I am sorry for the inconvenience.

**Comment by controlengineerinMLlearning** [comment]
Hi Vinthony, 

Is the code going to be recreated?

**Comment by vinthony** [comment]
I am sorry because I do not have enough time for the code.
