### ISSUE TITLE
Training ss and sr

### ISSUE THREAD

**Issue by controlengineerinMLlearning** [vinthony/ghost-free-shadow-removal#43]
Dear Vinthony,

Thank you again for the great code. I am however having a question regarding training:
train_ss and train_sr both perform a training task.   I do not fully understand the difference between the goal of both models and if I should train both. Since training is expensive (computationally), I would like to know which training to perform.

If I understand correctly:
The train_ss file generates the shadow synthesis model, so the weights Hierarchical feature layer aggregation 
The train_sr file generates the shadow removal model, actually removing the shadow using the SSP

I am not sure if I understand correctly. Hopefully you are able to help me.

C

**Comment by vinthony** [comment]
Yes, you understand correctly.

**Comment by controlengineerinMLlearning** [comment]
If I would like to run it, which of the two models should I load for testing? because they both have the same name. The training/testing process is not completely clear to me.

The process I understand: 
 - run train_ss. This generates 3 ckpt files.
 - run train_sr. This also generates 3 ckpt files with the same name. 
 - run train.sr --is_testing = 0 -> we would like to test the data. But how do I load all of the 6 above files correctly? I am not able to fully understand this principle. 

I think the --task argument in train_sr should be the save location of the 3 ckpt files of the train_ss algorithm? That this file uses the results of this code?

**Comment by vinthony** [comment]
`--task` is an argument to specify the *name* of the save folder, which should not same.

You only need to care about the usage/checkpoint of `train_sr.py`.  The checkpoint from `train_ss.py` is not needed when shadow removal, `train_ss.py` is only a method for semi-supervised data augmentation.

**Comment by yuanyufang** [comment]
> Yes, you understand correctly.
I would like to ask why the code can not run on GPU, because I set UAE_GPU to 0 or 1, but the terminal does not show using GPU, using CPU（我想问下为什么代码不能运行在GPU下，因为我把UAE_GPU设为0或者1，但是在终端里面没有显示使用GPU，在使用CPU，代码是只能运行在CPU环境下吗）
