### ISSUE TITLE
COLAB NOTEBOOK DEMO, not working

### ISSUE THREAD

**Issue by Hamzat0014** [vinthony/ghost-free-shadow-removal#47]
The colab notebook for demo purpose is not working. Its says that "Tensorflow 1.x can't be used on colab, upgrade your code to tensorflow 2.x"
I even tried to install tensorflow and CUDA, cudnn version manually but still didn't succeeded. 
Please helo

**Comment by Hamzat0014** [comment]
exact error encountered is, "ValueError: Tensorflow 1 is unsupported in Colab."

**Comment by vinthony** [comment]
Fixed the colab through reinstalling the TensorFlow 1.x.
