### ISSUE TITLE
Training on SRD dataset

### ISSUE THREAD

**Issue by vladtamas** [vinthony/ghost-free-shadow-removal#6]
Hello,

Do you have any updates regarding the remaining step in the training?

**Comment by vinthony** [comment]
Hi, thanks for your attention.

I’m kind of busy recently.

The Experiments on SRD dataset can be easily run by renaming the folders of SRD dataset using the style of ISTD.

More details of training on SRD will be released in the next two or three days.

**Comment by vinthony** [comment]
fixed

**Comment by jinyeying** [comment]
Hi,

I succesfully run the training script of ISTD dataset. However, after renaming SRD dataset, there is an issue training the SRD dataset.

[i] Total 2680 training images, first path of real image is /dataset/SRD_Dataset/train//train_A/_MG_4722.jpg.

  File "train_sr_srd.py", line 145, in <module>
    iminput,imtarget,maskgt = parpare_image(current_img_id,(neww,newh),da=True,stage=['_M','_C','_B'])
  File "/ghost-free-shadow-removal/utils.py", line 66, in parpare_image
    imtarget = encode_image(val_path.replace('_A',stage[1]),(imw,imh))
  File "/ghost-free-shadow-removal/utils.py", line 57, in encode_image
    input_image=cv2.resize(np.float32(input_image),(imw,imh),cv2.INTER_CUBIC)
TypeError: src is not a numpy array, neither a scalar

seems still some problem dealing with inputing SRD training images.
